[workspace]
allow_dirty = false
changelog_update = true
dependencies_update = true
git_release_enable = true
semver_check = true

[[package]]
name = "const-secret"
git_release_enable = true
changelog_update = true

[changelog]
protect_breaking_commits = true
